using GeoGen.Core;
using GeoGen.Utilities;

namespace GeoGen.Generator
{
    /// <summary>
    /// Represents a factory for creating new instances of a type <see cref="IArgumentsContainer"/>.
    /// NOTE: The implementation will be auto-generated by NInject. 
    /// </summary>
    public interface IArgumentsContainerFactory
    {
        /// <summary>
        /// Creates an empty arguments container.
        /// </summary>
        /// <returns>The arguments container.</returns>
        IContainer<Arguments> CreateContainer();
    }
}