namespace GeoGen.Analyzer
{
    /// <summary>
    /// Represents a factory that takes care of creating <see cref="IObjectsContainer"/>s.
    /// NOTE: The implementation will be auto-generated by NInject. 
    /// </summary>
    internal interface IObjectsContainerFactory
    {
        /// <summary>
        /// Creates an objects container.
        /// </summary>
        /// <returns>The objects container.</returns>
        IObjectsContainer CreateContainer();
    }
}