using GeoGen.Core;
using GeoGen.Utilities;
using System.Linq;

namespace GeoGen.Generator
{
    /// <summary>
    /// Represents a <see cref="Configuration"/> that was generated by the <see cref="Generator"/>.
    /// </summary>
    public class GeneratedConfiguration : Configuration
    {
        #region Public properties

        /// <summary>
        /// Gets or sets the previous configuration that was extended to obtain
        /// this one. This value will be null for the initial configuration.
        /// </summary>
        public GeneratedConfiguration PreviousConfiguration { get; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="GeneratedConfiguration"/> class 
        /// using a configuration that was extended and the object that should be added to it.
        /// </summary>
        /// <param name="currentConfiguration">The configuration that was extended.</param>
        /// <param name="newObject">The new object with which this configuration was extended.</param>
        /// <param name="id">The id of the configuration.</param>
        public GeneratedConfiguration(GeneratedConfiguration currentConfiguration, ConstructedConfigurationObject newObject, int id)
            : base(currentConfiguration.LooseObjectsHolder, currentConfiguration.ConstructedObjects.Concat(newObject.AsEnumerable()).ToList())
        {
            Id = id;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeneratedConfiguration"/> class 
        /// representing a configuration with no previous configuration.
        /// </summary>
        /// <param name="configuration">The configuration to be wrapped by this object.</param>
        /// <param name="id">The id of the configuration.</param>
        public GeneratedConfiguration(Configuration configuration, int id)
            : base(configuration.LooseObjectsHolder, configuration.ConstructedObjects)
        {
            Id = id;
        }

        #endregion
    }
}